import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import StyledInput from "../components/StyledInput";
import { router } from "../server/trpc/trpc";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const router = useRouter();

  const findTiktokUser = trpc.example.findTiktokUser.useMutation({
    onSuccess: (data) => {
      console.log("### data on success-", data);

      router.push(`/stats/${data.username}`);
    },
  });

  const [username, setUsername] = useState("");

  const handleSubmit = () => {
    findTiktokUser.mutate({ username });
  };

  return (
    <>
      <Head>
        <title>Tiktok Metrics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen max-w-2xl flex-col items-center justify-center p-4">
        <h1 className="mb-6 text-center font-generalsans text-[56px] font-extrabold leading-[64px] text-[#0F1D40] md:text-[56px]">
          TikTok Metrics
        </h1>
        <p className="mb-8 text-center font-generalsans text-[20px] leading-[32px] text-[#525C76]">
          Find out how the Creator’s last 10 videos performed.
        </p>
        <StyledInput
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          // error={true}
          // errorMessage="Account does not exist"
        />
        <button
          className="w-full cursor-pointer rounded-lg bg-[#6B53FF] py-3 px-4 text-sm font-bold text-white hover:shadow-button disabled:bg-[#EEEFF2] disabled:text-[#B2B7C2]"
          disabled={username === ""}
          onClick={handleSubmit}
        >
          Show Performance
        </button>
        {/* <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div> */}
      </main>
    </>
  );
};

export default Home;
